services:
  spelunker:
    image: ghcr.io/woeplanet/woeplanet-spelunker:latest
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /.env:/opt/woeplanet/.env
      - ./config/logging.yml:/opt/woeplanet/config/logging.yml
      - ./storage:/opt/woeplanet/storage
      - ./downloads:/opt/woeplanet/downloads
      - ./storage/cache:/opt/woeplanet/storage/cache
