---
version: 1
disable_existing_loggers: false
formatters:
  default:
    # "()": uvicorn.logging.DefaultFormatter
    format: '[%(asctime)s] [%(process)s] [%(levelname)s] [%(name)s] - %(message)s'
  access:
    # "()": uvicorn.logging.AccessFormatter
    format: '[%(asctime)s] [%(process)s] [%(levelname)s] [%(name)s] - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: false
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: false
  httpx:
    level: DEBUG
    handlers:
      - default
  httpx_retries:
    level: INFO
    handlers:
      - default
  httpcore:
    level: INFO
    handlers:
      - default
  pyrate_limiter:
    level: WARNING
    handlers:
      - default
  aiosqlite:
    level: WARNING
    handlers:
      - default
root:
  level: DEBUG
  handlers:
    - default
  propagate: false
